[package]
name = "desk_mirror"
version = "0.1.0"
edition = "2024"
keywords = [
  "desk_mirror"
]

[dependencies]
chrono = "0.4.41"
reqwest = { version="0.12.20", features = ["blocking"] }
serde = { version="1.0.219", features = ["derive"] }
serde_json = "1.0.140"
toml = "0.8.23"
